export interface Chapter {
  chapterNumber: number;
  name: string;
  englishName: string;
  arabicName: string;
}

export const CHAPTERS: Chapter[] = [
  {
    chapterNumber: 1,
    name: "Al-Faatiha",
    englishName: "The Opening",
    arabicName: "سُوْرَةُ الْفَاتِحَةِ",
  },
  {
    chapterNumber: 2,
    name: "Al-Baqara",
    englishName: "The Cow",
    arabicName: "سُوْرَةُ البَقَرَةِ",
  },
  {
    chapterNumber: 3,
    name: "Aal-i-Imraan",
    englishName: "The Family of Imraan",
    arabicName: "سُوْرَةُ اٰلِ عِمْرٰنَ",
  },
  {
    chapterNumber: 4,
    name: "An-Nisaa",
    englishName: "The Women",
    arabicName: "سُوْرَةُ النِّسَآءِ",
  },
  {
    chapterNumber: 5,
    name: "Al-Maaida",
    englishName: "The Table",
    arabicName: "سُوْرَةُ المَآئِدَةِ",
  },
  {
    chapterNumber: 6,
    name: "Al-An'aam",
    englishName: "The Cattle",
    arabicName: "سُوْرَةُ الْاَنْعَامِ",
  },
  {
    chapterNumber: 7,
    name: "Al-A'raaf",
    englishName: "The Heights",
    arabicName: "سُوْرَةُ الْاَعْرَافِ",
  },
  {
    chapterNumber: 8,
    name: "Al-Anfaal",
    englishName: "The Spoils of War",
    arabicName: "سُوْرَةُ الْاَنْفَالِ",
  },
  {
    chapterNumber: 9,
    name: "At-Tawba",
    englishName: "The Repentance",
    arabicName: "سُوْرَةُ التَّوْبَةِ",
  },
  {
    chapterNumber: 10,
    name: "Yunus",
    englishName: "Jonas",
    arabicName: "سُوْرَةُ يُوْنُسَ",
  },
  {
    chapterNumber: 11,
    name: "Hud",
    englishName: "Hud",
    arabicName: "سُوْرَةُ هُوْدٍ",
  },
  {
    chapterNumber: 12,
    name: "Yusuf",
    englishName: "Joseph",
    arabicName: "سُوْرَةُ يُوسُفَ",
  },
  {
    chapterNumber: 13,
    name: "Ar-Ra'd",
    englishName: "The Thunder",
    arabicName: "سُوْرَةُ الرَّعْدِ",
  },
  {
    chapterNumber: 14,
    name: "Ibrahim",
    englishName: "Abraham",
    arabicName: "سُوْرَةُ اِبْرَاهِيْمَ",
  },
  {
    chapterNumber: 15,
    name: "Al-Hijr",
    englishName: "The Rock",
    arabicName: "سُوْرَةُ الْحِجْرِ",
  },
  {
    chapterNumber: 16,
    name: "An-Nahl",
    englishName: "The Bee",
    arabicName: "سُوْرَةُ النَّحْلِ",
  },
  {
    chapterNumber: 17,
    name: "Al-Israa",
    englishName: "The Night Journey",
    arabicName: "سُوْرَةُ الإِسۡرَاءِ",
  },
  {
    chapterNumber: 18,
    name: "Al-Kahf",
    englishName: "The Cave",
    arabicName: "سُوْرَةُ الْكَهْفِ",
  },
  {
    chapterNumber: 19,
    name: "Maryam",
    englishName: "Mary",
    arabicName: "سُوْرَةُ مَرْيَمَ",
  },
  {
    chapterNumber: 20,
    name: "Taa-Haa",
    englishName: "Taa-Haa",
    arabicName: "سُوْرَةُ طٰهٰ",
  },
  {
    chapterNumber: 21,
    name: "Al-Anbiyaa",
    englishName: "The Prophets",
    arabicName: "سُوْرَةُ الْاَنْۣبِيَآءِ",
  },
  {
    chapterNumber: 22,
    name: "Al-Hajj",
    englishName: "The Pilgrimage",
    arabicName: "سُوْرَةُ الْحَجِّ",
  },
  {
    chapterNumber: 23,
    name: "Al-Muminoon",
    englishName: "The Believers",
    arabicName: "سُوْرَةُ الْمُؤْمِنُوْنَ",
  },
  {
    chapterNumber: 24,
    name: "An-Noor",
    englishName: "The Light",
    arabicName: "سُوْرَةُ النُّوْرِ",
  },
  {
    chapterNumber: 25,
    name: "Al-Furqaan",
    englishName: "The Criterion",
    arabicName: "سُوْرَةُ الْفُرْقَانِ",
  },
  {
    chapterNumber: 26,
    name: "Ash-Shu'araa",
    englishName: "The Poets",
    arabicName: "سُوْرَةُ الشُّعَرَآءِ",
  },
  {
    chapterNumber: 27,
    name: "An-Naml",
    englishName: "The Ant",
    arabicName: "سُوْرَةُ النَّمْلِ",
  },
  {
    chapterNumber: 28,
    name: "Al-Qasas",
    englishName: "The Stories",
    arabicName: "سُوْرَةُ الْقَصَصِ",
  },
  {
    chapterNumber: 29,
    name: "Al-Ankaboot",
    englishName: "The Spider",
    arabicName: "سُوْرَةُ الْعَنْكَبُوْتِ",
  },
  {
    chapterNumber: 30,
    name: "Ar-Room",
    englishName: "The Romans",
    arabicName: "سُوْرَةُ الرُّوْمِ",
  },
  {
    chapterNumber: 31,
    name: "Luqman",
    englishName: "Luqman",
    arabicName: "سُوْرَةُ لُقْمَانَ",
  },
  {
    chapterNumber: 32,
    name: "As-Sajda",
    englishName: "The Prostration",
    arabicName: "سُوْرَةُ السَّجْدَةِ",
  },
  {
    chapterNumber: 33,
    name: "Al-Ahzaab",
    englishName: "The Clans",
    arabicName: "سُوْرَةُ الْاَحْزَابِ",
  },
  {
    chapterNumber: 34,
    name: "Saba",
    englishName: "Sheba",
    arabicName: "سُوْرَةُ سَبَاٍ",
  },
  {
    chapterNumber: 35,
    name: "Faatir",
    englishName: "The Originator",
    arabicName: "سُوْرَةُ فَاطِرٍ",
  },
  {
    chapterNumber: 36,
    name: "Yaseen",
    englishName: "Yaseen",
    arabicName: "سُوْرَةُ يٰسٓ",
  },
  {
    chapterNumber: 37,
    name: "As-Saaffaat",
    englishName: "Those drawn up in Ranks",
    arabicName: "سُوْرَةُ الصَّافَّاتِ",
  },
  {
    chapterNumber: 38,
    name: "Saad",
    englishName: "The letter Saad",
    arabicName: "سُوْرَةُ صٓ",
  },
  {
    chapterNumber: 39,
    name: "Az-Zumar",
    englishName: "The Groups",
    arabicName: "سُوْرَةُ الزُّمَرِ",
  },
  {
    chapterNumber: 40,
    name: "Ghafir",
    englishName: "The Forgiver",
    arabicName: "سُوْرَةُ الْمُؤْمِنِ",
  },
  {
    chapterNumber: 41,
    name: "Fussilat",
    englishName: "Explained in detail",
    arabicName: "سُوْرَةُ فُصِّلَتۡ",
  },
  {
    chapterNumber: 42,
    name: "Ash-Shura",
    englishName: "Consultation",
    arabicName: "سُوْرَةُ الشُّوْرٰي",
  },
  {
    chapterNumber: 43,
    name: "Az-Zukhruf",
    englishName: "Ornaments of gold",
    arabicName: "سُوْرَةُ الزُّخْرُفِ",
  },
  {
    chapterNumber: 44,
    name: "Ad-Dukhaan",
    englishName: "The Smoke",
    arabicName: "سُوْرَةُ الدُّخَانِ",
  },
  {
    chapterNumber: 45,
    name: "Al-Jaathiya",
    englishName: "Crouching",
    arabicName: "سُوْرَةُ الْجَاثِيَةِ",
  },
  {
    chapterNumber: 46,
    name: "Al-Ahqaf",
    englishName: "The Dunes",
    arabicName: "سُوْرَةُ الْاَحْقَافِ",
  },
  {
    chapterNumber: 47,
    name: "Muhammad",
    englishName: "Muhammad",
    arabicName: "سُوْرَةُ مُحَمَّدٍ",
  },
  {
    chapterNumber: 48,
    name: "Al-Fath",
    englishName: "The Victory",
    arabicName: "سُوْرَةُ الْفَتْحِ",
  },
  {
    chapterNumber: 49,
    name: "Al-Hujuraat",
    englishName: "The Inner Apartments",
    arabicName: "سُوْرَةُ الْحُجُراتِ",
  },
  {
    chapterNumber: 50,
    name: "Qaaf",
    englishName: "The letter Qaaf",
    arabicName: "سُوْرَةُ قٓ",
  },
  {
    chapterNumber: 51,
    name: "Adh-Dhaariyat",
    englishName: "The Winnowing Winds",
    arabicName: "سُوْرَةُ الذَّارِياتِ",
  },
  {
    chapterNumber: 52,
    name: "At-Tur",
    englishName: "The Mount",
    arabicName: "سُوْرَةُ الطُّوْرِ",
  },
  {
    chapterNumber: 53,
    name: "An-Najm",
    englishName: "The Star",
    arabicName: "سُوْرَةُ النَّجْمِ",
  },
  {
    chapterNumber: 54,
    name: "Al-Qamar",
    englishName: "The Moon",
    arabicName: "سُوْرَةُ الْقَمَرِ",
  },
  {
    chapterNumber: 55,
    name: "Ar-Rahmaan",
    englishName: "The Beneficent",
    arabicName: "سُوْرَةُ الرَّحْمٰنِ",
  },
  {
    chapterNumber: 56,
    name: "Al-Waaqia",
    englishName: "The Inevitable",
    arabicName: "سُوْرَةُ الْوَاقِعَةِ",
  },
  {
    chapterNumber: 57,
    name: "Al-Hadid",
    englishName: "The Iron",
    arabicName: "سُوْرَةُ الْحَدِيْدِ",
  },
  {
    chapterNumber: 58,
    name: "Al-Mujaadila",
    englishName: "The Pleading Woman",
    arabicName: "سُوْرَةُ الْمُجَادَلَةِ",
  },
  {
    chapterNumber: 59,
    name: "Al-Hashr",
    englishName: "The Exile",
    arabicName: "سُوْرَةُ الْحَشْرِ",
  },
  {
    chapterNumber: 60,
    name: "Al-Mumtahana",
    englishName: "She that is to be examined",
    arabicName: "سُوْرَةُ الْمُمْتَحِنَةِ",
  },
  {
    chapterNumber: 61,
    name: "As-Saff",
    englishName: "The Ranks",
    arabicName: "سُوْرَةُ الصَّفِّ",
  },
  {
    chapterNumber: 62,
    name: "Al-Jumu'a",
    englishName: "Friday",
    arabicName: "سُوْرَةُ الْجُمُعَةِ",
  },
  {
    chapterNumber: 63,
    name: "Al-Munaafiqoon",
    englishName: "The Hypocrites",
    arabicName: "سُوْرَةُ الْمُنَافِقُوْنَ",
  },
  {
    chapterNumber: 64,
    name: "At-Taghaabun",
    englishName: "Mutual Disillusion",
    arabicName: "سُوْرَةُ التَّغَابُنِ",
  },
  {
    chapterNumber: 65,
    name: "At-Talaaq",
    englishName: "Divorce",
    arabicName: "سُوْرَةُ الطَّلَاقِ",
  },
  {
    chapterNumber: 66,
    name: "At-Tahrim",
    englishName: "The Prohibition",
    arabicName: "سُوْرَةُ التَّحْرِيْمِ",
  },
  {
    chapterNumber: 67,
    name: "Al-Mulk",
    englishName: "The Sovereignty",
    arabicName: "سُوْرَةُ الْمُلْكِ",
  },
  {
    chapterNumber: 68,
    name: "Al-Qalam",
    englishName: "The Pen",
    arabicName: "سُوْرَةُ الْقَلَمِ",
  },
  {
    chapterNumber: 69,
    name: "Al-Haaqqa",
    englishName: "The Reality",
    arabicName: "سُوْرَةُ الْحَآقَّةِ",
  },
  {
    chapterNumber: 70,
    name: "Al-Ma'aarij",
    englishName: "The Ascending Stairways",
    arabicName: "سُوْرَةُ الْمَعَارِجِ",
  },
  {
    chapterNumber: 71,
    name: "Nooh",
    englishName: "Noah",
    arabicName: "سُوْرَةُ نُوْحٍ",
  },
  {
    chapterNumber: 72,
    name: "Al-Jinn",
    englishName: "The Jinn",
    arabicName: "سُوْرَةُ الْجِنِّ",
  },
  {
    chapterNumber: 73,
    name: "Al-Muzzammil",
    englishName: "The Enshrouded One",
    arabicName: "سُوْرَةُ الْمُزَّمِّلِ",
  },
  {
    chapterNumber: 74,
    name: "Al-Muddaththir",
    englishName: "The Cloaked One",
    arabicName: "سُوْرَةُ الْمُدَّثِّرِ",
  },
  {
    chapterNumber: 75,
    name: "Al-Qiyaama",
    englishName: "The Resurrection",
    arabicName: "سُوْرَةُ الْقِيَامَةِ",
  },
  {
    chapterNumber: 76,
    name: "Al-Insaan",
    englishName: "Man",
    arabicName: "سُوْرَةُ الدَّهْرِ",
  },
  {
    chapterNumber: 77,
    name: "Al-Mursalaat",
    englishName: "The Emissaries",
    arabicName: "سُوْرَةُ الْمُرْسَلَاتِ",
  },
  {
    chapterNumber: 78,
    name: "An-Naba",
    englishName: "The Announcement",
    arabicName: "سُوْرَةُ النَّبَاِ",
  },
  {
    chapterNumber: 79,
    name: "An-Naazi'aat",
    englishName: "Those who drag forth",
    arabicName: "سُوْرَةُ النَّازِعَاتِ",
  },
  {
    chapterNumber: 80,
    name: "Abasa",
    englishName: "He frowned",
    arabicName: "سُوْرَةُ عَبَسَ",
  },
  {
    chapterNumber: 81,
    name: "At-Takwir",
    englishName: "The Overthrowing",
    arabicName: "سُوْرَةُ التَّكْوِيْرِ",
  },
  {
    chapterNumber: 82,
    name: "Al-Infitaar",
    englishName: "The Cleaving",
    arabicName: "سُوْرَةُ الْاِنْفِطَارِ",
  },
  {
    chapterNumber: 83,
    name: "Al-Mutaffifin",
    englishName: "Defrauding",
    arabicName: "سُوْرَةُ المُطَفِّفِيْنَ",
  },
  {
    chapterNumber: 84,
    name: "Al-Inshiqaaq",
    englishName: "The Splitting Open",
    arabicName: "سُوْرَةُ الاِنْشِقَاقِ",
  },
  {
    chapterNumber: 85,
    name: "Al-Burooj",
    englishName: "The Constellations",
    arabicName: "سُوْرَةُ الْبُرُوْجِ",
  },
  {
    chapterNumber: 86,
    name: "At-Taariq",
    englishName: "The Morning Star",
    arabicName: "سُوْرَةُ الطَّارِقِ",
  },
  {
    chapterNumber: 87,
    name: "Al-A'laa",
    englishName: "The Most High",
    arabicName: "سُوْرَةُ الْاَعْلٰي",
  },
  {
    chapterNumber: 88,
    name: "Al-Ghaashiya",
    englishName: "The Overwhelming",
    arabicName: "سُوْرَةُ الْغَاشِيَةِ",
  },
  {
    chapterNumber: 89,
    name: "Al-Fajr",
    englishName: "The Dawn",
    arabicName: "سُوْرَةُ الْفَجْرِ",
  },
  {
    chapterNumber: 90,
    name: "Al-Balad",
    englishName: "The City",
    arabicName: "سُوْرَةُ الْبَلَدِ",
  },
  {
    chapterNumber: 91,
    name: "Ash-Shams",
    englishName: "The Sun",
    arabicName: "سُوْرَةُ الشَّمْسِ",
  },
  {
    chapterNumber: 92,
    name: "Al-Lail",
    englishName: "The Night",
    arabicName: "سُوْرَةُ الَّيْلِ",
  },
  {
    chapterNumber: 93,
    name: "Ad-Dhuhaa",
    englishName: "The Morning Hours",
    arabicName: "سُوْرَةُ الضُّحٰي",
  },
  {
    chapterNumber: 94,
    name: "Ash-Sharh",
    englishName: "The Consolation",
    arabicName: "سُوْرَةُ الشَّرْحِ",
  },
  {
    chapterNumber: 95,
    name: "At-Tin",
    englishName: "The Fig",
    arabicName: "سُوْرَةُ التِّيْنِ",
  },
  {
    chapterNumber: 96,
    name: "Al-Alaq",
    englishName: "The Clot",
    arabicName: "سُوْرَةُ الْعَلَقِ",
  },
  {
    chapterNumber: 97,
    name: "Al-Qadr",
    englishName: "The Power, Fate",
    arabicName: "سُوْرَةُ الْقَدْرِ",
  },
  {
    chapterNumber: 98,
    name: "Al-Bayyina",
    englishName: "The Evidence",
    arabicName: "سُوْرَةُ الْبَيِّنَةِ",
  },
  {
    chapterNumber: 99,
    name: "Az-Zalzala",
    englishName: "The Earthquake",
    arabicName: "سُوْرَةُ الزِّلْزَالِ",
  },
  {
    chapterNumber: 100,
    name: "Al-Aadiyaat",
    englishName: "The Chargers",
    arabicName: "سُوْرَةُ العٰدِيٰتِ",
  },
  {
    chapterNumber: 101,
    name: "Al-Qaari'a",
    englishName: "The Calamity",
    arabicName: "سُوْرَةُ الْقَارِعَةِ",
  },
  {
    chapterNumber: 102,
    name: "At-Takaathur",
    englishName: "Competition",
    arabicName: "سُوْرَةُ التَّكَاثُرِ",
  },
  {
    chapterNumber: 103,
    name: "Al-Asr",
    englishName: "The Declining Day, Epoch",
    arabicName: "سُوْرَةُ الْعَصْرِ",
  },
  {
    chapterNumber: 104,
    name: "Al-Humaza",
    englishName: "The Traducer",
    arabicName: "سُوْرَةُ الْهُمَزَةِ",
  },
  {
    chapterNumber: 105,
    name: "Al-Fil",
    englishName: "The Elephant",
    arabicName: "سُوْرَةُ الْفِيْلِ",
  },
  {
    chapterNumber: 106,
    name: "Quraish",
    englishName: "Quraysh",
    arabicName: "سُوْرَةُ قُرَيْشٍ",
  },
  {
    chapterNumber: 107,
    name: "Al-Maa'un",
    englishName: "Almsgiving",
    arabicName: "سُوْرَةُ الْمَاعُوْنِ",
  },
  {
    chapterNumber: 108,
    name: "Al-Kawthar",
    englishName: "Abundance",
    arabicName: "سُوْرَةُ الْكَوْثَرِ",
  },
  {
    chapterNumber: 109,
    name: "Al-Kaafiroon",
    englishName: "The Disbelievers",
    arabicName: "سُوْرَةُ الْكَافِرُوْنَ",
  },
  {
    chapterNumber: 110,
    name: "An-Nasr",
    englishName: "Divine Support",
    arabicName: "سُوْرَةُ النَّصْرِ",
  },
  {
    chapterNumber: 111,
    name: "Al-Masad",
    englishName: "The Palm Fibre",
    arabicName: "سُوْرَةُ المَسَدِ",
  },
  {
    chapterNumber: 112,
    name: "Al-Ikhlaas",
    englishName: "Sincerity",
    arabicName: "سُوْرَةُ الْاِخْلَاصِ",
  },
  {
    chapterNumber: 113,
    name: "Al-Falaq",
    englishName: "The Dawn",
    arabicName: "سُوْرَةُ الْفَلَقِ",
  },
  {
    chapterNumber: 114,
    name: "An-Naas",
    englishName: "Mankind",
    arabicName: "سُوْرَةُ النَّاسِ",
  },
];

export function getChapter(chapterNumber: number): Chapter | undefined {
  return CHAPTERS.find((chapter) => chapter.chapterNumber === chapterNumber);
}
